/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsDestinationRouteImport } from './routes/destinations/$destination'
import { Route as DestinationsDestinationSelectionRouteImport } from './routes/destinations/$destination.$selection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsDestinationRoute = DestinationsDestinationRouteImport.update({
  id: '/destinations/$destination',
  path: '/destinations/$destination',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsDestinationSelectionRoute =
  DestinationsDestinationSelectionRouteImport.update({
    id: '/$selection',
    path: '/$selection',
    getParentRoute: () => DestinationsDestinationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations/$destination': typeof DestinationsDestinationRouteWithChildren
  '/destinations': typeof DestinationsIndexRoute
  '/destinations/$destination/$selection': typeof DestinationsDestinationSelectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations/$destination': typeof DestinationsDestinationRouteWithChildren
  '/destinations': typeof DestinationsIndexRoute
  '/destinations/$destination/$selection': typeof DestinationsDestinationSelectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations/$destination': typeof DestinationsDestinationRouteWithChildren
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/$destination/$selection': typeof DestinationsDestinationSelectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/destinations/$destination'
    | '/destinations'
    | '/destinations/$destination/$selection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/destinations/$destination'
    | '/destinations'
    | '/destinations/$destination/$selection'
  id:
    | '__root__'
    | '/'
    | '/destinations/$destination'
    | '/destinations/'
    | '/destinations/$destination/$selection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsDestinationRoute: typeof DestinationsDestinationRouteWithChildren
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$destination': {
      id: '/destinations/$destination'
      path: '/destinations/$destination'
      fullPath: '/destinations/$destination'
      preLoaderRoute: typeof DestinationsDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$destination/$selection': {
      id: '/destinations/$destination/$selection'
      path: '/$selection'
      fullPath: '/destinations/$destination/$selection'
      preLoaderRoute: typeof DestinationsDestinationSelectionRouteImport
      parentRoute: typeof DestinationsDestinationRoute
    }
  }
}

interface DestinationsDestinationRouteChildren {
  DestinationsDestinationSelectionRoute: typeof DestinationsDestinationSelectionRoute
}

const DestinationsDestinationRouteChildren: DestinationsDestinationRouteChildren =
  {
    DestinationsDestinationSelectionRoute:
      DestinationsDestinationSelectionRoute,
  }

const DestinationsDestinationRouteWithChildren =
  DestinationsDestinationRoute._addFileChildren(
    DestinationsDestinationRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsDestinationRoute: DestinationsDestinationRouteWithChildren,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
